<h1><em><strong>Task Intro:&nbsp;</strong></em></h1>


<p>Task: You have a lot of screenshots from some tool like <strong>aquatone</strong>.&nbsp;<a href="https://github.com/michenriksen/aquatone" target="_blank">https://github.com/michenriksen/aquatone</a>. Instead of manually looking at each web page for finding interesting page, we built a classifier to find the interesting page.&nbsp;</p>

<p>We classify each screenshot into one of the following categories:</p>

<ol>
	<li>&nbsp;Custom 404 Page: The status code might not be 404 but the page is</li>
	<li>Login Page</li>
	<li>Old looking website</li>
	<li>Home Page</li>
</ol>

<h3><em><u><strong>Image Classification Task, use a CNN model.</strong></u></em></h3>

<h3>&nbsp;</h3>


<h1 id="Intro-to-CNN-models: "><em><strong>Intro to CNN models:&nbsp;</strong></em><br />
&nbsp;</h1>


<p><img alt="Learn more complex feats as more layers increased. " src="https://miro.medium.com/max/2052/1*yZQjaMKHjm1HzDF4t4juzg.png" style="width: 1026px; height: 730px;" /></p>


ref;  https://towardsdatascience.com/image-classifier-cats-vs-dogs-with-convolutional-neural-networks-cnns-and-google-colabs-4e9af21ae7a8

<p id="Each-layer-learns-to-recognise-a-shape-and-as-we-move-to-deeper-layers,-the-complexity-of-the-shape-increases.-"><strong><em>Each layer learns to recognise a shape and as we move to deeper layers, the complexity of the shape increases. </em></strong></p>

<p>&nbsp;</p>

<p><strong><em>SImilar to how you learn to draw.</em></strong></p>

<p><strong><em>Initially it starts with learning simple straight lines, next it moves on to squares and rectangles, next layer would learn about curves, next layer would learn specific things specific to data and so on</em></strong></p>


<p><img alt="" src="https://miro.medium.com/max/1356/1*-OM6jQTMNACDX2vAh_lvMQ.png" style="width: 678px; height: 462px;" /></p>


<h2 id="Make-some-imports:"><em>Make some imports:</em></h2>


In [4]:
import os
import random
import sys
import shutil
import numpy as np
import pandas as pd 
import cv2

## Read Data

In [5]:
labels_file =  "/Users/mayanksatnalika/Desktop/eyeballer/eyeballer-training-data/labels.csv"
labels_csv = pd.read_csv(labels_file)

In [6]:
labels_csv[:3]

filename  custom404  login  \
0  0000000000000000.055e4022955875f9177527a7fdcf5...      False  False   
1            http-007.comdoesnotexist12431231231.png       True  False   
2  0000000000000000.241e88e7083efa1e78b3a4b01c4eb...      False  False   

   homepage  oldlooking  evaluation  
0     False       False        True  
1     False       False        True  
2     False       False       False

In [7]:
train_files = labels_csv.loc[labels_csv['evaluation'] == False ]
test_files = labels_csv.loc[labels_csv['evaluation'] == True ]

In [8]:
len(train_files)

10489

In [9]:
train_dir = "/Users/mayanksatnalika/Desktop/eyeballer/eyeballer-training-data/train_images/"
test_dir =  "/Users/mayanksatnalika/Desktop/eyeballer/eyeballer-training-data/test_images/"
%mkdir /Users/mayanksatnalika/Desktop/eyeballer/eyeballer-training-data/train_images/
%mkdir /Users/mayanksatnalika/Desktop/eyeballer/eyeballer-training-data/test_images/

mkdir: /Users/mayanksatnalika/Desktop/eyeballer/eyeballer-training-data/train_images/: File exists
mkdir: /Users/mayanksatnalika/Desktop/eyeballer/eyeballer-training-data/test_images/: File exists


In [10]:
def remove_img(image, orignal_image_dir, new_image_dir):
    
    shutil.move(orignal_image_dir + image, new_image_dir + image )

### Run Once

In [8]:
for file_ in list(train_files['filename']):
    try:
        remove_img(file_, image_dir, train_dir )
        
    except Exception as e:
        print ("exc: ", e)
     
    
for file_ in list(test_files['filename']):
    try:
        remove_img(file_, image_dir, test_dir )
    except Exception as e:
        print ("exc: ", e)


exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name '

exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name '

exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name '

exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name '

exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name '

exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name '

exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name '

exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name '

exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name 'image_dir' is not defined
exc:  name '

# The interesting stuff:

In [11]:
import tensorflow as tf

<h3><u><strong><em>TENSORFLOW</em></strong></u></h3>

<h3>An open source library used for deep learning.</h3>

<p>&nbsp;</p>

<blockquote>
<p>TensorFlow is an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of tools, libraries and community resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML powered application...</p>
</blockquote>


<h3><em><u><strong>KERAS</strong></u></em></h3>

<p>&nbsp;</p>

<p>Tensorflow provides a lot of operations, 90% of&nbsp; tasks you need to be done is something which would be covered by some pre-available code.</p>

<p>Keras is a wrapper over tensorflow which provides simple interface to do do most of the deep learning stuff you will ever need.&nbsp;&nbsp;</p>

<p><br />
Recently tensorflow 2.0 was released which made Keras as a part of itself.&nbsp;</p>


<p id="The-keras-pipeline:">The keras pipeline:</p>

<p>&nbsp;&nbsp;&nbsp;&nbsp; You define a model.</p>

<p>&nbsp;&nbsp;&nbsp;&nbsp; A model is made of the following components:&nbsp;</p>

<ol>
	<li>
	<p>An input Layer&nbsp;</p>
	</li>
	<li>
	<p>The middel layers&nbsp;</p>
	</li>
	<li>
	<p>The ouput layer.&nbsp;</p>
	</li>
</ol>

<p>After a model if defined, we&nbsp; fit the data on the model&nbsp;</p>

<p>&nbsp;</p>

<pre>
model = Sequential()
</pre>

<pre>
model.add(Conv2D(32, kernel_size=(5, 5), strides=(1, 1),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;activation=&#39;relu&#39;,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
model.add(Conv2D(64, (5, 5), activation=&#39;relu&#39;))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(1000, activation=&#39;relu&#39;))
model.add(Dense(num_classes, activation=&#39;softmax&#39;))
</pre>

<pre data-line-offset="0" data-start="1">
<code>model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.SGD(lr=0.01),
              metrics=[&#39;accuracy&#39;])</code></pre>

<pre>
model.fit ( input_data , needed_output) </pre>

<p><br />
&nbsp;</p>


In [12]:
image_dir = "/Users/mayanksatnalika/Desktop/eyeballer/eyeballer-training-data/images/"
image_width, image_height = 224, 224
input_shape = (image_width, image_height, 3)
DATA_LABELS = ["custom404", "login", "homepage", "oldlooking"]

In [13]:
def model(input_shape, summary= False):
    model = tf.keras.Sequential()
    pretrained_layer = tf.keras.applications.mobilenet.MobileNet(weights='imagenet', include_top=False, input_shape=input_shape)
    model.add(pretrained_layer)
    model.add(tf.keras.layers.GlobalAveragePooling2D())
    model.add(tf.keras.layers.Dense(8, activation="relu"))
    model.add(tf.keras.layers.Dropout(0.5))
    model.add(tf.keras.layers.Dense(len(DATA_LABELS), activation="sigmoid"))

    model.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
                        loss="binary_crossentropy",
                        metrics=["accuracy"])
    if summary:
        print(model.summary())
    return model

In [14]:
custom_model = model(input_shape, summary = True )

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
mobilenet_1.00_224 (Model)   (None, 7, 7, 1024)        3228864   
_________________________________________________________________
global_average_pooling2d (Gl (None, 1024)              0         
_________________________________________________________________
dense (Dense)                (None, 8)                 8200      
_________________________________________________________________
dropout (Dropout)            (None, 8)                 0         
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 36        
Total params: 3,237,100
Trainable params: 3,215,212
Non-trainable params: 21,888
_________________________________________________________________
None


<h3><u><em><strong>Augmentation</strong></em></u></h3>

<p id="If-I-dont'-have-many-images-to-train-a-model..."><em><strong>If I dont&#39; have many images to train a model...</strong></em></p>


In [1]:
import Augmentor


In [16]:
Augmentor.__file__

'/Users/mayanksatnalika/Desktop/eyeballer/Augmentor/__init__.py'

In [17]:
import Augmentor
augmented_ouptut_dir =  "/Users/mayanksatnalika/Desktop/eyeballer/eyeballer-training-data/augmented_train_images/"
augmentor = Augmentor.Pipeline(source_directory=train_dir, output_directory=augmented_ouptut_dir)
augmentor.zoom(probability=0.75, min_factor=0.8, max_factor=1.2)
augmentor.random_color(probability=0.75, min_factor=0.5, max_factor=1.0)
augmentor.random_contrast(probability=0.75, min_factor=0.8, max_factor=1.0)
augmentor.random_brightness(probability=0.75, min_factor=0.8, max_factor=1.2)
augmentor.random_erasing(probability=0.75, rectangle_area=0.15)

Initialised with 10485 image(s) found.
Output directory set to /Users/mayanksatnalika/Desktop/eyeballer/eyeballer-training-data/augmented_train_images/.

<p><img alt="" src="https://i.ibb.co/5FrW8qM/Screenshot-2019-12-13-at-6-46-32-PM.png " style="border-width: 10px; border-style: solid; width: 1515px; height: 600px;" /></p>


In [ ]:
augmentor.sample(10000,multi_threaded=True)

<h3 id="Read-images-data-produced-by-augmentor"><strong><em>Read images data produced by augmentor and match with actual labels</em></strong></h3>


In [14]:
from tensorflow.keras.applications.mobilenet import preprocess_input as preprocess_for_mobilenet
def make_suitable_for_eyeballer(image):
    image_array = np.array(image).astype('uint8')
    image_array = preprocess_for_mobilenet(image_array)
    return image_array

In [15]:

def load_image( infilename, print_file=False ) :
    if print_file:
        print (infilename.split("_original_")[-1].split(".png")[0]+".png")
    label_file_path = infilename.split("_original_")[-1].split(".png")[0]+".png"
    arr = cv2.imread(infilename)
    arr = np.resize(arr, input_shape)
    arr = make_suitable_for_eyeballer(arr)
    return arr, label_file_path

In [16]:
train_files = os.listdir(augmented_ouptut_dir)

In [17]:
len(train_files)

9974

In [18]:
all_train_images = [ ]
all_train_labels = [ ]

for file_ in train_files:
    image_path = augmented_ouptut_dir  + file_
    image_, label_path  = load_image(image_path)
    all_train_images.append(image_)
    row_ = labels_csv.loc[labels_csv['filename'] ==  label_path ] 
    c_404, login , home, old = row_['custom404'],  row_['login'],  row_['homepage'],  row_['oldlooking'] 
    all_train_labels.append( (int(c_404), int(login ), int(home), int(old)) )

In [19]:
all_train_images = np.array(all_train_images)

In [20]:
type(all_train_images)

numpy.ndarray

<h1 id="Fit-the-model"><em>Fit the model:</em></h1>


In [29]:
custom_model.fit(x=all_train_images[:1000], y = np.asarray(all_train_labels)[:1000] , epochs=1)

Train on 1000 samples
Epoch 1/2
1000/1000 [==============================] - 79s 79ms/sample - loss: 0.6576 - accuracy: 0.7053
Epoch 2/2
  64/1000 [>.............................] - ETA: 1:09 - loss: 0.5537 - accuracy: 0.7734

KeyboardInterrupt: 

<h3 id="Using-the-provided-model"><em>Using the provided model</em></h3>


In [21]:
def model(input_shape, summary= False):
    model = tf.keras.Sequential()
    pretrained_layer = tf.keras.applications.mobilenet.MobileNet(weights='imagenet', include_top=False, input_shape=input_shape)
    model.add(pretrained_layer)
    model.add(tf.keras.layers.GlobalAveragePooling2D())
    model.add(tf.keras.layers.Dense(256, activation="relu"))
    model.add(tf.keras.layers.Dropout(0.5))
    model.add(tf.keras.layers.Dense(128, activation="relu"))
    model.add(tf.keras.layers.Dropout(0.2))
    model.add(tf.keras.layers.Dense(len(DATA_LABELS), activation="sigmoid"))

    model.compile(optimizer=tf.keras.optimizers.Adam(0.0005),
                       loss="binary_crossentropy",
                       metrics=["accuracy"])
    if summary:
        print(model.summary())
    return model

In [22]:
pretrained_model = model(input_shape=input_shape)

In [23]:
model_weights_file = "/Users/mayanksatnalika/Desktop/eyeballer/eyeballer-training-data/bishop-fox-pretrained-v1.h5"

In [24]:
pretrained_model.load_weights(model_weights_file)

<p><strong>!! TIP:&nbsp;</strong></p>

<pre>
np.argmax( arr )
</pre>

<p><em>Gives the <strong>index of the maximum item from our array</strong>.&nbsp;</em></p>


In [30]:
val_dictionary = {0 : "custom404",
                 1: "login",
                 2: "homepage",
                 3: "old-looking"}


for idx, val in enumerate(all_train_images):
    preds = pretrained_model.predict(x=  np.array([val]) )
    print (val_dictionary[np.argmax(preds)], val_dictionary[np.argmax(all_train_labels[idx])])
     
    print (   preds , all_train_labels[idx])
        
    
    print ('----------') 

custom404 custom404
[[0.4079596  0.09633075 0.4055859  0.03830348]] (1, 0, 0, 0)
----------
homepage homepage
[[0.2958889  0.0284768  0.6315753  0.00332812]] (0, 0, 1, 0)
----------
login custom404
[[0.12579282 0.33041024 0.13338818 0.17369737]] (0, 0, 0, 0)
----------
custom404 login
[[0.6501574  0.09038671 0.23564708 0.01473801]] (0, 1, 0, 0)
----------
login login
[[0.15076205 0.74802446 0.16733402 0.1109838 ]] (0, 1, 0, 0)
----------
login login
[[3.5275004e-04 9.9797267e-01 4.1881897e-03 1.8456613e-03]] (0, 1, 0, 0)
----------
custom404 custom404
[[0.7202028  0.16286239 0.20306541 0.03782647]] (1, 0, 0, 0)
----------
homepage homepage
[[1.1401633e-02 4.2777516e-02 9.8062623e-01 5.2679057e-04]] (0, 0, 1, 0)
----------
homepage homepage
[[0.01236951 0.4742648  0.9818788  0.00450658]] (0, 0, 1, 0)
----------
custom404 custom404
[[0.87840766 0.01644889 0.13237794 0.00422046]] (1, 0, 0, 0)
----------
custom404 custom404
[[0.7037134  0.02169873 0.02027516 0.00810234]] (1, 0, 0, 0)
-----

login login
[[2.8774227e-06 9.9995279e-01 4.7104640e-04 1.2240560e-05]] (0, 1, 0, 0)
----------
homepage custom404
[[0.31472418 0.37537137 0.633336   0.3584343 ]] (1, 0, 0, 0)
----------
homepage homepage
[[0.00438361 0.60919523 0.990995   0.00163228]] (0, 0, 1, 0)
----------
homepage login
[[1.7137616e-04 8.8769698e-01 9.9840999e-01 1.1437808e-03]] (0, 1, 1, 0)
----------
homepage homepage
[[0.016807   0.08202844 0.9681488  0.00271015]] (0, 0, 1, 0)
----------
homepage homepage
[[1.1587936e-02 1.0447001e-01 9.7794318e-01 8.4401522e-04]] (0, 0, 1, 0)
----------
homepage homepage
[[0.00749979 0.27909443 0.96935755 0.07518635]] (0, 0, 1, 1)
----------
login login
[[1.1466211e-06 9.9997246e-01 5.4422906e-04 4.9841542e-06]] (0, 1, 0, 0)
----------
custom404 custom404
[[0.43002334 0.03220255 0.27240774 0.03912402]] (1, 0, 0, 0)
----------
custom404 custom404
[[0.29602572 0.10804417 0.2208576  0.05846279]] (0, 0, 0, 0)
----------
login login
[[1.1632941e-05 9.9903935e-01 1.1736379e-01 5.4700

login login
[[2.4857625e-08 9.9999976e-01 1.6155515e-06 4.4042434e-08]] (0, 1, 0, 0)
----------
login login
[[3.2695429e-08 9.9999833e-01 1.0626580e-04 4.7599525e-07]] (0, 1, 0, 0)
----------
custom404 custom404
[[0.502149   0.12028581 0.35281366 0.03263254]] (1, 0, 0, 0)
----------
login login
[[8.8151688e-07 9.9999046e-01 9.7884207e-05 3.1634352e-06]] (0, 1, 0, 0)
----------
homepage login
[[0.00480916 0.06014754 0.98572415 0.00125369]] (0, 1, 1, 0)
----------
custom404 custom404
[[0.30176246 0.07784098 0.03850268 0.04997222]] (0, 0, 0, 0)
----------
custom404 custom404
[[0.9062925  0.00356464 0.12317821 0.00101684]] (1, 0, 0, 0)
----------
homepage homepage
[[1.2681417e-02 1.2443781e-02 9.7187567e-01 3.8233440e-04]] (0, 0, 1, 0)
----------
homepage login
[[0.00195253 0.5412134  0.9953186  0.00101966]] (0, 1, 1, 0)
----------
old-looking old-looking
[[0.0130635  0.04796967 0.6510372  0.89619225]] (0, 0, 0, 1)
----------
homepage old-looking
[[0.12642705 0.06171658 0.3234297  0.161476

homepage homepage
[[2.6684804e-04 8.6358863e-01 9.9819416e-01 6.6015549e-04]] (0, 0, 1, 1)
----------
homepage login
[[0.00110104 0.815165   0.9941858  0.00360692]] (0, 1, 1, 0)
----------
homepage login
[[0.08584307 0.27301145 0.85388595 0.0126091 ]] (0, 1, 0, 0)
----------
custom404 custom404
[[9.9993896e-01 6.8570102e-07 3.6818076e-06 3.6210915e-07]] (1, 0, 0, 0)
----------
login custom404
[[0.2576428  0.44311264 0.38648492 0.39981645]] (1, 0, 0, 0)
----------
login login
[[0.00176311 0.9733513  0.3785964  0.00250192]] (0, 1, 0, 0)
----------
custom404 custom404
[[0.08826143 0.08529545 0.00184593 0.01121959]] (1, 0, 0, 0)
----------
login custom404
[[0.0397617  0.3378306  0.00310193 0.02309656]] (0, 0, 0, 0)
----------
login login
[[2.3081068e-07 9.9999785e-01 9.4405032e-06 5.4076384e-07]] (0, 1, 0, 0)
----------
custom404 custom404
[[0.7151612  0.00582145 0.00855782 0.02261144]] (0, 0, 0, 0)
----------
homepage homepage
[[0.23362525 0.16889936 0.654045   0.00897302]] (0, 0, 1, 0)
-

login login
[[2.2968119e-07 9.9999249e-01 1.7087001e-04 2.6581683e-06]] (0, 1, 0, 0)
----------
homepage homepage
[[0.09379688 0.4201812  0.8860438  0.01348742]] (0, 0, 1, 0)
----------
login login
[[1.2155650e-06 9.9995065e-01 2.0036765e-03 2.6929338e-05]] (0, 1, 0, 0)
----------
homepage custom404
[[0.37167612 0.04555274 0.6331559  0.00980808]] (1, 0, 0, 0)
----------
custom404 login
[[0.1793513  0.08810594 0.01539276 0.05338243]] (0, 1, 0, 0)
----------
homepage login
[[0.00434262 0.5863544  0.99010545 0.00231398]] (0, 1, 1, 0)
----------
custom404 custom404
[[0.75090235 0.02287524 0.06020904 0.03292735]] (1, 0, 0, 0)
----------
login login
[[1.1492759e-06 9.9996877e-01 7.4663351e-04 5.4620673e-06]] (0, 1, 0, 0)
----------
custom404 custom404
[[0.66456556 0.0106705  0.3337189  0.00275949]] (0, 0, 0, 0)
----------
homepage homepage
[[0.00301752 0.7852222  0.9876507  0.00367945]] (0, 0, 1, 0)
----------
login login
[[4.5341367e-05 9.9879885e-01 3.0530041e-02 1.0227362e-04]] (0, 1, 0, 

custom404 login
[[0.5635813  0.3962545  0.21937191 0.03043784]] (0, 1, 0, 0)
----------
homepage homepage
[[0.24617933 0.08004314 0.65810883 0.01979858]] (0, 0, 1, 0)
----------
homepage homepage
[[0.10756303 0.02878688 0.87575    0.00482126]] (0, 0, 1, 0)
----------
custom404 custom404
[[9.9978071e-01 3.7998179e-06 9.9866566e-06 2.1877877e-06]] (1, 0, 0, 0)
----------
login login
[[3.1367106e-06 9.9970078e-01 4.1732099e-02 1.7232180e-05]] (0, 1, 0, 0)
----------
login login
[[0.03905785 0.791048   0.7892493  0.02079247]] (0, 1, 1, 0)
----------
homepage homepage
[[0.02812203 0.38018012 0.9643035  0.00544886]] (0, 0, 1, 0)
----------
homepage homepage
[[0.42586747 0.04528774 0.52555805 0.00435194]] (0, 0, 1, 0)
----------
login login
[[2.3092130e-06 9.9999607e-01 7.2324638e-06 2.7793729e-07]] (0, 1, 0, 0)
----------
custom404 login
[[0.4756945  0.08173656 0.05587641 0.03349658]] (0, 1, 0, 0)
----------
old-looking homepage
[[0.00399228 0.28073713 0.88847154 0.89055294]] (0, 0, 1, 1)
--

homepage homepage
[[0.02484513 0.06118727 0.95945007 0.00103751]] (0, 0, 1, 0)
----------
homepage custom404
[[0.08272394 0.1336501  0.55880326 0.28043   ]] (0, 0, 0, 0)
----------
homepage homepage
[[0.0313639  0.05148134 0.93668413 0.00526687]] (0, 0, 1, 0)
----------
homepage custom404
[[0.1081458 0.600608  0.8377033 0.1027033]] (1, 0, 0, 0)
----------
login login
[[6.2692260e-07 9.9998724e-01 1.7492354e-04 9.2349474e-06]] (0, 1, 0, 0)
----------
login login
[[3.9465012e-05 9.9674100e-01 4.4310811e-01 8.8195120e-05]] (0, 1, 0, 0)
----------
homepage login
[[3.8919158e-03 4.6250349e-01 9.9427819e-01 3.2784548e-04]] (0, 1, 1, 0)
----------
login login
[[7.7816895e-07 9.9999297e-01 6.6254201e-05 7.8078040e-07]] (0, 1, 0, 0)
----------
homepage login
[[0.01750643 0.77570945 0.92035645 0.02670157]] (0, 1, 0, 0)
----------
login custom404
[[0.00892462 0.94812435 0.04166155 0.05388821]] (0, 0, 0, 0)
----------
homepage homepage
[[2.875012e-03 4.183988e-03 9.936812e-01 9.811475e-05]] (0, 0,

custom404 custom404
[[0.8196157  0.00274628 0.10605773 0.00158138]] (1, 0, 0, 0)
----------
homepage homepage
[[2.2393651e-04 2.4567395e-01 9.9925512e-01 1.9531643e-04]] (0, 0, 1, 0)
----------
homepage homepage
[[0.00956187 0.4179074  0.8672391  0.696811  ]] (0, 0, 1, 1)
----------
homepage homepage
[[0.00212796 0.5623584  0.9893584  0.02834468]] (0, 0, 1, 0)
----------
homepage login
[[1.7779827e-03 5.3675473e-01 9.9553901e-01 3.8701965e-04]] (0, 1, 1, 0)
----------
login custom404
[[0.07621177 0.7588625  0.10719637 0.16802165]] (0, 0, 0, 0)
----------
homepage homepage
[[1.3126089e-04 7.3132229e-01 9.9937719e-01 2.5526743e-04]] (0, 0, 1, 0)
----------
custom404 custom404
[[0.1117655  0.07320366 0.05786908 0.10379817]] (0, 0, 0, 0)
----------
login login
[[1.0683642e-03 9.9161094e-01 7.3332734e-02 8.7581226e-04]] (0, 1, 0, 0)
----------
homepage homepage
[[0.00563563 0.45081332 0.98839825 0.00136002]] (0, 0, 1, 0)
----------
login login
[[2.2272027e-06 9.9995410e-01 7.0549734e-04 2.2

homepage homepage
[[0.06013007 0.6297945  0.8586501  0.01251437]] (0, 0, 1, 0)
----------
custom404 custom404
[[0.9627959  0.00373468 0.00877623 0.00124547]] (1, 0, 0, 0)
----------
login login
[[5.2696387e-06 9.9994004e-01 5.1153795e-04 1.4674564e-05]] (0, 1, 0, 0)
----------
homepage login
[[0.04459531 0.6573439  0.7981118  0.01616405]] (0, 1, 0, 1)
----------
login login
[[6.1815030e-07 9.9991226e-01 3.0018367e-02 5.6805984e-06]] (0, 1, 0, 0)
----------
login login
[[4.8661951e-07 9.9999547e-01 3.6452908e-05 4.6685543e-07]] (0, 1, 0, 0)
----------
login login
[[4.5316723e-05 9.9866426e-01 3.9820842e-02 1.1570091e-04]] (0, 1, 0, 0)
----------
homepage custom404
[[0.30348492 0.12896964 0.59566873 0.09454285]] (1, 0, 0, 0)
----------
custom404 custom404
[[0.4650513  0.1591562  0.10340926 0.08090601]] (0, 0, 0, 0)
----------
custom404 custom404
[[0.8868668  0.00491705 0.16494496 0.00165747]] (1, 0, 0, 0)
----------
login old-looking
[[0.20031911 0.37792882 0.1661918  0.03527398]] (0, 0,

homepage login
[[0.0231092  0.079996   0.94108534 0.015073  ]] (0, 1, 1, 0)
----------
homepage homepage
[[0.01519856 0.26069036 0.9695071  0.00770786]] (0, 0, 1, 0)
----------
homepage login
[[8.9650523e-05 8.9307797e-01 9.9772102e-01 5.3878529e-03]] (0, 1, 1, 0)
----------
login login
[[8.6642231e-08 9.9999833e-01 2.4698422e-05 1.5892508e-07]] (0, 1, 0, 0)
----------
login login
[[1.9338421e-07 9.9999785e-01 1.9184619e-05 2.6697202e-07]] (0, 1, 0, 0)
----------
login login
[[0.0142487  0.9523757  0.00759445 0.00760092]] (0, 1, 0, 0)
----------
homepage custom404
[[0.03045157 0.6228347  0.9327047  0.01589582]] (1, 1, 0, 0)
----------
custom404 custom404
[[0.6567646  0.04054455 0.16233471 0.05298073]] (1, 0, 0, 0)
----------
custom404 custom404
[[0.7076682  0.00812401 0.29020968 0.00356376]] (1, 0, 0, 0)
----------
homepage login
[[1.0785922e-04 9.5206243e-01 9.9797064e-01 3.1154620e-04]] (0, 1, 1, 0)
----------
login login
[[4.7702770e-07 9.9998975e-01 1.3219479e-04 5.9357253e-06]] (0

custom404 custom404
[[0.454351   0.18740106 0.3961049  0.19661234]] (1, 0, 0, 0)
----------
custom404 custom404
[[9.9983478e-01 1.9460688e-06 7.0124597e-06 1.3063452e-06]] (1, 0, 0, 0)
----------
homepage homepage
[[0.00100098 0.787996   0.9931853  0.03781879]] (0, 0, 1, 1)
----------
homepage custom404
[[0.23134921 0.08244435 0.7046583  0.00403824]] (1, 0, 0, 0)
----------
homepage homepage
[[0.0138324  0.44958284 0.96319026 0.02587291]] (0, 0, 1, 0)
----------
homepage homepage
[[6.8692025e-04 7.0399708e-01 9.8963708e-01 1.2666820e-01]] (0, 0, 1, 1)
----------
homepage homepage
[[0.00287704 0.48248047 0.9816     0.03054987]] (0, 0, 1, 1)
----------
login custom404
[[0.01229369 0.8994908  0.6719663  0.00688783]] (1, 0, 0, 0)
----------
login homepage
[[0.01582379 0.8700609  0.62912714 0.00765656]] (0, 0, 1, 0)
----------
custom404 custom404
[[0.7575278  0.04213833 0.24735998 0.01914603]] (0, 0, 0, 0)
----------
homepage login
[[2.4064905e-04 7.3288989e-01 9.9909997e-01 4.1583236e-04]]

homepage custom404
[[0.3297185  0.03266332 0.6430732  0.01388228]] (1, 0, 0, 0)
----------
homepage custom404
[[0.01437171 0.3495974  0.97702575 0.00252911]] (1, 0, 0, 0)
----------
homepage homepage
[[0.17284733 0.02202692 0.7907415  0.00301769]] (0, 0, 1, 0)
----------
login login
[[5.8080041e-06 9.9994767e-01 3.6364692e-04 2.2539957e-06]] (0, 1, 0, 0)
----------
homepage homepage
[[0.00421252 0.52561784 0.9441051  0.5446022 ]] (0, 0, 1, 1)
----------
login old-looking
[[0.04388362 0.8127235  0.45458204 0.02351048]] (0, 0, 0, 1)
----------
homepage homepage
[[0.01700311 0.2852354  0.96717125 0.00500983]] (0, 0, 1, 0)
----------
custom404 custom404
[[0.9126844  0.01636381 0.06293485 0.00293393]] (1, 0, 0, 0)
----------
login login
[[0.09049211 0.3431166  0.00610351 0.03993066]] (0, 1, 0, 0)
----------
homepage old-looking
[[0.11618547 0.38132027 0.66692907 0.3331488 ]] (0, 0, 0, 1)
----------
login login
[[2.9988792e-03 9.9598372e-01 2.4351985e-03 6.3677266e-04]] (0, 1, 0, 0)
--------

login homepage
[[0.1985152  0.66608775 0.38110918 0.16403905]] (0, 0, 1, 0)
----------
custom404 custom404
[[0.8394711  0.00612996 0.07611319 0.00451271]] (1, 0, 0, 0)
----------
homepage homepage
[[0.03796196 0.43732533 0.8799269  0.1897848 ]] (0, 0, 1, 1)
----------
homepage homepage
[[1.0452693e-03 4.7575437e-02 9.9758732e-01 1.1221324e-04]] (0, 0, 1, 0)
----------
homepage login
[[0.0026152  0.73149484 0.9931623  0.00123646]] (0, 1, 1, 0)
----------
homepage homepage
[[0.00409709 0.7486487  0.980736   0.01014739]] (0, 0, 1, 0)
----------
homepage homepage
[[0.12810692 0.08760808 0.6079817  0.29472318]] (0, 0, 1, 1)
----------
custom404 homepage
[[0.49291033 0.07005984 0.42657134 0.02026532]] (0, 0, 1, 0)
----------
login custom404
[[0.05092973 0.81020665 0.33887807 0.09307004]] (1, 0, 0, 0)
----------
custom404 custom404
[[9.9577063e-01 1.6644712e-04 1.1493389e-03 5.1796880e-05]] (1, 0, 0, 0)
----------
homepage homepage
[[1.8354599e-01 5.5229180e-03 7.5921035e-01 4.1171422e-04]] (

login login
[[0.00758527 0.97190607 0.11443044 0.00502029]] (0, 1, 0, 0)
----------
homepage login
[[1.5639186e-02 1.6165408e-01 9.7717959e-01 9.3110662e-04]] (0, 1, 1, 0)
----------
custom404 login
[[0.12911594 0.12668593 0.01079018 0.0150946 ]] (0, 1, 0, 0)
----------
homepage homepage
[[9.1163040e-04 5.9332675e-01 9.9717784e-01 9.3934493e-04]] (0, 0, 1, 1)
----------
homepage homepage
[[0.00474632 0.17623922 0.99005264 0.00128321]] (0, 0, 1, 0)
----------
homepage homepage
[[2.3564221e-03 7.7600211e-02 9.9212730e-01 4.8763512e-04]] (0, 0, 1, 0)
----------
custom404 login
[[0.50302285 0.20981583 0.12278077 0.10832022]] (0, 1, 0, 0)
----------
homepage homepage
[[0.15127915 0.18378955 0.7670287  0.02639601]] (0, 0, 1, 0)
----------
custom404 custom404
[[0.19377652 0.04225084 0.00481508 0.01788663]] (1, 0, 0, 0)
----------
login login
[[3.6947409e-04 9.9397320e-01 9.0167664e-02 2.9130522e-03]] (0, 1, 0, 0)
----------
homepage homepage
[[0.00461292 0.7574254  0.9868486  0.00445751]] (0,

login login
[[0.02656084 0.9470101  0.0084945  0.01127643]] (0, 1, 0, 0)
----------
homepage homepage
[[0.00818789 0.530832   0.9601478  0.1054161 ]] (0, 0, 1, 0)
----------
custom404 custom404
[[0.9700336  0.00757405 0.02734384 0.0025542 ]] (1, 0, 0, 0)
----------
homepage homepage
[[4.7421918e-04 1.3439958e-01 9.9714631e-01 5.4178708e-03]] (0, 0, 1, 1)
----------
homepage homepage
[[5.3185626e-04 4.3285835e-01 9.9837554e-01 6.6069805e-04]] (0, 0, 1, 0)
----------
homepage login
[[0.002768   0.7206927  0.98953104 0.00409462]] (0, 1, 0, 0)
----------
custom404 custom404
[[0.84874076 0.01324718 0.08306582 0.0017586 ]] (1, 0, 0, 0)
----------
homepage homepage
[[0.00099797 0.6845362  0.99588037 0.00143056]] (0, 0, 1, 0)
----------
login login
[[0.01478691 0.83047426 0.6650383  0.04640874]] (0, 1, 1, 1)
----------
custom404 custom404
[[0.6940434  0.10536236 0.29782635 0.01977829]] (1, 0, 0, 0)
----------
homepage homepage
[[0.00139642 0.66590154 0.9958047  0.00114812]] (0, 0, 1, 0)
------

homepage custom404
[[0.24449672 0.02083709 0.62471014 0.00498846]] (1, 0, 0, 0)
----------
homepage homepage
[[0.24152979 0.32606107 0.6252974  0.04700294]] (0, 0, 1, 0)
----------
custom404 homepage
[[0.8286796  0.01785687 0.0936544  0.00350731]] (0, 0, 1, 0)
----------
login login
[[2.9615863e-05 9.9941945e-01 9.7175669e-03 9.7152275e-05]] (0, 1, 0, 0)
----------
login login
[[0.13972895 0.73001534 0.08151897 0.08241045]] (0, 1, 0, 0)
----------
custom404 custom404
[[0.51361924 0.09692879 0.4505285  0.02349322]] (1, 0, 0, 0)
----------
homepage login
[[0.00937121 0.6673126  0.97322494 0.00343285]] (0, 1, 1, 0)
----------
homepage custom404
[[0.40671408 0.12161066 0.42745215 0.08962481]] (1, 0, 0, 0)
----------
login login
[[1.16827046e-07 9.99997616e-01 2.60603374e-05 6.20579158e-07]] (0, 1, 0, 0)
----------
homepage login
[[3.4924640e-04 9.3875879e-01 9.8571742e-01 1.1735024e-03]] (0, 1, 1, 1)
----------
custom404 custom404
[[9.9369472e-01 1.5037888e-04 1.4920367e-04 9.9722987e-05]]

homepage homepage
[[0.12198216 0.04263001 0.45674407 0.38277575]] (0, 0, 1, 1)
----------
login login
[[2.2151502e-08 9.9999964e-01 3.7257685e-06 9.1760278e-08]] (0, 1, 0, 0)
----------
homepage homepage
[[0.01406736 0.6982771  0.8995555  0.00834651]] (0, 0, 1, 0)
----------
homepage homepage
[[0.0035541  0.15715083 0.98990065 0.00540996]] (0, 0, 1, 0)
----------
homepage login
[[0.02775357 0.6514002  0.87425065 0.13587943]] (0, 1, 0, 0)
----------
login login
[[0.15230815 0.30151144 0.08338911 0.08160547]] (0, 1, 0, 0)
----------
old-looking old-looking
[[0.24670641 0.2396728  0.16698162 0.26141623]] (0, 0, 0, 1)
----------
login login
[[0.06036037 0.14324555 0.01058563 0.03576552]] (0, 1, 0, 0)
----------
custom404 custom404
[[0.885097   0.002082   0.02474234 0.00199051]] (1, 0, 0, 0)
----------
custom404 custom404
[[0.34437007 0.04657415 0.2074994  0.02361942]] (0, 0, 0, 0)
----------
homepage login
[[3.3372486e-04 8.7723941e-01 9.9592990e-01 2.8852331e-03]] (0, 1, 1, 0)
----------


custom404 custom404
[[0.6785299  0.03136377 0.2684271  0.01402065]] (1, 0, 0, 0)
----------
login login
[[6.5809442e-04 9.9844629e-01 6.2536215e-04 4.3890785e-04]] (0, 1, 0, 0)
----------
login login
[[1.2740832e-04 9.9826813e-01 1.3288240e-02 9.1027247e-04]] (0, 1, 0, 0)
----------
old-looking custom404
[[0.21550894 0.14149159 0.36198094 0.70467776]] (1, 0, 0, 0)
----------
homepage login
[[0.0083216  0.42085782 0.9754097  0.00729852]] (0, 1, 1, 0)
----------
login login
[[4.3392693e-06 9.9993193e-01 9.4181974e-04 2.6845697e-05]] (0, 1, 0, 0)
----------
homepage homepage
[[0.00105973 0.4910654  0.9967443  0.00352075]] (0, 0, 1, 0)
----------
custom404 custom404
[[9.9473840e-01 9.6184747e-05 8.2180806e-05 5.9429043e-05]] (1, 0, 0, 0)
----------
homepage login
[[0.03390204 0.724451   0.8886118  0.02586679]] (0, 1, 1, 0)
----------
login custom404
[[0.16364019 0.6568594  0.01165233 0.00275385]] (1, 0, 0, 0)
----------
login login
[[0.09864009 0.20076498 0.0158573  0.0363755 ]] (0, 1, 0, 

homepage homepage
[[0.10649667 0.10295274 0.8604177  0.00783301]] (0, 0, 1, 0)
----------
homepage homepage
[[2.4080100e-04 8.3484489e-01 9.9878544e-01 5.3136278e-04]] (0, 0, 1, 0)
----------
custom404 old-looking
[[0.8224583  0.0054314  0.05961947 0.00701418]] (0, 0, 0, 1)
----------
homepage homepage
[[3.4971863e-03 2.9068586e-01 9.9411714e-01 3.2808469e-04]] (0, 0, 1, 0)
----------
custom404 custom404
[[0.74061126 0.01333964 0.28374967 0.00328793]] (1, 0, 0, 0)
----------
old-looking homepage
[[0.00215095 0.08058953 0.90551937 0.91647637]] (0, 0, 1, 1)
----------
login custom404
[[0.1355434  0.20661351 0.09779888 0.11106271]] (0, 0, 0, 0)
----------
homepage login
[[8.8498986e-04 6.8229944e-01 9.9714357e-01 1.5134622e-03]] (0, 1, 1, 0)
----------
login login
[[0.03140432 0.91357565 0.01257338 0.02273651]] (0, 1, 0, 0)
----------
homepage custom404
[[3.5408642e-03 1.7652452e-01 9.9407285e-01 6.1075995e-04]] (1, 0, 0, 0)
----------
login custom404
[[0.02340735 0.81666183 0.79777294 0.

homepage login
[[4.6204784e-04 7.9172140e-01 9.9753332e-01 1.1520858e-03]] (0, 1, 1, 0)
----------
custom404 old-looking
[[0.8756412  0.01057628 0.06751764 0.00727539]] (0, 0, 0, 1)
----------
homepage homepage
[[0.2617829  0.05600834 0.6944982  0.01320476]] (0, 0, 1, 0)
----------
homepage custom404
[[0.11534594 0.59329396 0.7034078  0.17690405]] (1, 0, 0, 1)
----------
homepage homepage
[[0.00472034 0.05390769 0.9906148  0.00116667]] (0, 0, 1, 0)
----------
homepage login
[[7.4739842e-04 3.4329772e-01 9.9622750e-01 2.3995521e-02]] (0, 1, 1, 1)
----------
homepage login
[[0.06213598 0.17554358 0.8964987  0.01865539]] (0, 1, 1, 0)
----------
homepage old-looking
[[0.00340366 0.4624602  0.9904917  0.00666929]] (0, 0, 0, 1)
----------
custom404 custom404
[[0.62844205 0.17072296 0.29817158 0.02811389]] (1, 0, 0, 0)
----------
homepage login
[[0.02207349 0.7061699  0.93921244 0.0240729 ]] (0, 1, 0, 0)
----------
login login
[[6.4534233e-06 9.9944502e-01 1.5549181e-01 2.1750808e-05]] (0, 1,

homepage login
[[6.3606026e-04 5.1204723e-01 9.9836904e-01 2.1503121e-04]] (0, 1, 1, 0)
----------
homepage homepage
[[5.2362966e-04 6.8761617e-01 9.4822508e-01 8.5641235e-01]] (0, 0, 1, 1)
----------
login login
[[0.00230376 0.98741305 0.0628378  0.00426689]] (0, 1, 0, 0)
----------
homepage homepage
[[1.8645171e-03 1.0762645e-01 9.9646461e-01 2.3168222e-04]] (0, 0, 1, 0)
----------
custom404 custom404
[[0.60068476 0.12507449 0.3785414  0.06774943]] (1, 0, 0, 0)
----------
custom404 custom404
[[0.20044304 0.04075133 0.01016311 0.00704034]] (0, 0, 0, 0)
----------
homepage old-looking
[[0.00424189 0.61497885 0.96315765 0.14956973]] (0, 0, 0, 1)
----------
login custom404
[[0.03545249 0.934798   0.01908398 0.03563567]] (1, 0, 0, 0)
----------
homepage login
[[1.9442289e-04 9.5931858e-01 9.9462503e-01 1.4207498e-04]] (0, 1, 1, 0)
----------
homepage login
[[0.00246227 0.5876018  0.9929006  0.01062126]] (0, 1, 1, 0)
----------
homepage login
[[9.2160702e-04 5.6158864e-01 9.9678767e-01 2.0

homepage custom404
[[0.10082237 0.619344   0.7569308  0.05113688]] (1, 0, 0, 0)
----------
homepage homepage
[[0.01503639 0.13964066 0.7776958  0.61956996]] (0, 0, 1, 1)
----------
custom404 custom404
[[0.82098436 0.01957273 0.13405284 0.00404116]] (1, 0, 0, 0)
----------
custom404 custom404
[[9.9832326e-01 2.7219261e-05 1.6128461e-04 1.6179325e-05]] (1, 0, 0, 0)
----------
homepage homepage
[[0.00329458 0.6897029  0.99302787 0.00196905]] (0, 0, 1, 0)
----------
login login
[[1.9395056e-04 9.9841869e-01 8.9560719e-03 1.9341368e-03]] (0, 1, 0, 0)
----------
homepage homepage
[[0.00467809 0.47325042 0.98792225 0.00460356]] (0, 0, 1, 0)
----------
login login
[[0.0014801  0.99506986 0.01720804 0.0010797 ]] (0, 1, 0, 0)
----------
homepage homepage
[[1.5045377e-02 7.4402191e-02 9.7518456e-01 9.2883786e-04]] (0, 0, 1, 0)
----------
homepage homepage
[[0.21356487 0.06241585 0.6675559  0.0140755 ]] (0, 0, 1, 0)
----------
custom404 custom404
[[0.85344964 0.03285292 0.11514808 0.01175485]] (1,

homepage homepage
[[0.01735041 0.41744444 0.97012377 0.00414377]] (0, 0, 1, 0)
----------
homepage login
[[8.0043438e-04 9.3446040e-01 9.6054727e-01 1.2817105e-02]] (0, 1, 0, 0)
----------
homepage login
[[1.4352730e-05 9.6891654e-01 9.9911839e-01 1.1148390e-03]] (0, 1, 1, 0)
----------
homepage homepage
[[0.01804153 0.45880827 0.9702277  0.00617957]] (0, 0, 1, 0)
----------
login custom404
[[0.02695499 0.81104064 0.00347819 0.02332863]] (1, 0, 0, 0)
----------
custom404 homepage
[[0.7530931  0.08642745 0.2627132  0.02800316]] (0, 0, 1, 0)
----------
homepage homepage
[[0.00262912 0.71000856 0.9922862  0.00160413]] (0, 0, 1, 0)
----------
homepage login
[[2.4852445e-03 8.5761440e-01 9.7153282e-01 6.4940605e-04]] (0, 1, 1, 0)
----------
custom404 custom404
[[0.24957746 0.03881883 0.02701855 0.02571193]] (0, 0, 0, 0)
----------
custom404 custom404
[[0.4262117  0.22085048 0.15319318 0.07094577]] (1, 0, 0, 0)
----------
homepage homepage
[[1.3246710e-04 5.9751683e-01 9.9955422e-01 1.169896

login login
[[0.00561724 0.95806324 0.23566408 0.010085  ]] (0, 1, 0, 0)
----------
homepage login
[[0.01320011 0.3079138  0.9711403  0.00307347]] (0, 1, 1, 0)
----------
homepage homepage
[[0.00101075 0.7990099  0.99339575 0.00115791]] (0, 0, 1, 0)
----------
homepage login
[[0.03501903 0.32665122 0.84861547 0.10849487]] (0, 1, 1, 0)
----------
homepage homepage
[[5.2147225e-04 8.9744270e-01 9.9317920e-01 1.9591927e-04]] (0, 0, 1, 0)
----------
homepage homepage
[[3.9807663e-04 5.9689856e-01 9.9755305e-01 5.9012868e-03]] (0, 0, 1, 0)
----------
homepage custom404
[[0.40243578 0.08484519 0.57880765 0.00924035]] (1, 0, 0, 0)
----------
homepage homepage
[[0.01323372 0.2315694  0.9146779  0.31935203]] (0, 0, 1, 1)
----------
homepage custom404
[[0.36388522 0.2937594  0.53696775 0.01869387]] (1, 0, 0, 0)
----------
homepage login
[[2.3980046e-04 6.1353332e-01 9.9910057e-01 3.2873845e-04]] (0, 1, 1, 0)
----------
homepage login
[[0.02031823 0.29405212 0.9600761  0.00985487]] (0, 1, 1, 0)
-

homepage homepage
[[2.1857774e-04 8.3103560e-02 9.8466152e-01 9.0233374e-01]] (0, 0, 1, 1)
----------
custom404 custom404
[[0.8042537  0.03426078 0.05921184 0.00979149]] (1, 0, 0, 0)
----------
homepage homepage
[[0.00641762 0.05328833 0.9803941  0.00170604]] (0, 0, 1, 0)
----------
homepage homepage
[[1.0364428e-04 8.8970214e-01 9.9879199e-01 9.5837895e-04]] (0, 0, 1, 0)
----------
homepage custom404
[[0.44622144 0.32543936 0.46989897 0.04193912]] (1, 0, 0, 0)
----------
custom404 custom404
[[9.9944025e-01 6.5566742e-06 2.0979714e-05 4.5473712e-06]] (1, 0, 0, 0)
----------
homepage custom404
[[0.12864564 0.20490317 0.4547664  0.4361124 ]] (1, 0, 0, 0)
----------
login login
[[7.9352511e-05 9.9945837e-01 3.6340009e-03 4.5934208e-05]] (0, 1, 0, 0)
----------
homepage homepage
[[2.3502770e-03 6.7692506e-01 9.9457967e-01 8.4171549e-04]] (0, 0, 1, 0)
----------
homepage custom404
[[0.00519715 0.88060886 0.94212556 0.00318966]] (1, 0, 0, 0)
----------
custom404 custom404
[[9.9979359e-01 6.4

login old-looking
[[3.1079387e-04 9.9893135e-01 1.1396707e-03 3.0176408e-04]] (0, 0, 0, 1)
----------
homepage custom404
[[0.3068305  0.01203428 0.7116898  0.00191343]] (1, 0, 0, 0)
----------
login login
[[5.9686753e-04 9.9735355e-01 4.4466760e-03 1.3808175e-03]] (0, 1, 0, 0)
----------
custom404 custom404
[[0.9428711  0.00225137 0.0183708  0.00098856]] (1, 0, 0, 0)
----------


KeyboardInterrupt: 

<h3 id="Trying-on-own-image"><strong><em>Trying on own image:</em></strong></h3>


In [20]:
convertable_image_array, _  = load_image("/Users/mayanksatnalika/Documents/Screenshot 2019-12-13 at 8.09.38 PM.png")

In [21]:
convertable_image_array.shape

(224, 224, 3)

In [22]:
pretrained_model.predict(x=  np.array([convertable_image_array]) )

array([[0.0454767 , 0.11028412, 0.04578311, 0.01404571]], dtype=float32)